USE SCHEMAXXX

-- SELECT ITEM TO ANALYSE
DECLARE @ITEM AS INT
SET @ITEM = 435

IF OBJECT_ID('TEMPDB..#TEMP_1') IS NOT NULL
		DROP TABLE #TEMP_1
	CREATE TABLE #TEMP_1 (TXN_ID DECIMAL (23,15), ITEM_ID INT, ROW_ID INT)
	INSERT INTO #TEMP_1
	SELECT TXN_ID, ITEM_ID, ROW_NUMBER() OVER (PARTITION BY TXN_ID ORDER BY ITEM_ID) ROW_ID FROM dbo.BA_Transactions

	-- GET MAXIMUM NUMBER OF UNIQUE ITEM IN TRANSCTION
	DECLARE @MAX_NUM_ITEM AS INT
	SET @MAX_NUM_ITEM = (
		SELECT MAX(ROW_ID) FROM #TEMP_1
	)

	DECLARE @COUNTER AS INT
	DECLARE @ITEM_STATEMENT AS VARCHAR(MAX)
	DECLARE @PIVOT_STATEMENT AS VARCHAR(MAX)
	DECLARE @SQL_STATEMENT AS NVARCHAR(MAX)

	SET @ITEM_STATEMENT = ''
	SET @PIVOT_STATEMENT = ''
	SET @SQL_STATEMENT = ''
	SET @COUNTER = 1

	WHILE @COUNTER <= @MAX_NUM_ITEM
	BEGIN
		SET @PIVOT_STATEMENT += '[' + CAST(@COUNTER AS VARCHAR(5)) + ']'
		IF @COUNTER < @MAX_NUM_ITEM
		BEGIN
			SET @ITEM_STATEMENT += '+ '','' + '
			SET @PIVOT_STATEMENT += ','
		END 

		SET @COUNTER += 1
				
	END

	SET @SQL_STATEMENT = 
		'
		IF OBJECT_ID(''TEMPDB..##TEMP_2'') IS NOT NULL
			DROP TABLE ##TEMP_2
		SELECT COUNT(DISTINCT TXN_ID) NUM_TXN, ' + @PIVOT_STATEMENT + ' INTO ##TEMP_2 FROM (
			SELECT TXN_ID, ' + @PIVOT_STATEMENT +  ' FROM (
				SELECT * FROM #TEMP_1
				) AS A
				PIVOT (SUM(ITEM_ID) FOR ROW_ID IN (' + @PIVOT_STATEMENT + '
		)) AS B
		) AS A
			GROUP BY ' + @PIVOT_STATEMENT +
			' ORDER BY COUNT(DISTINCT TXN_ID)'

	EXEC SP_EXECUTESQL @SQL_STATEMENT

	SET @SQL_STATEMENT = 
		'SELECT SUM(NUM_TXN)*1.0/(SELECT SUM(NUM_TXN) FROM ##TEMP_2) SUPPORT, ' + @PIVOT_STATEMENT + ' FROM ##TEMP_2
		GROUP BY ' + @PIVOT_STATEMENT +
		'ORDER BY SUM(NUM_TXN) DESC'

	EXECUTE SP_EXECUTESQL @SQL_STATEMENT